added user details api in backend
adad20/codeVisualForces pull request #1
Opened 2020-08-27 14:47 UTC by adad20

2020-08-27 15:59 UTC, ChoukseyKhushbu commented on index.js
> +       res.send({profiledata: profileData.data.result});
The API call returns `status` along with `result`

Add the following code at line 14 - 
```
let {status, result, comment} = profileData.data;
if(status === "OK"){
     res.status(200).send(result);
}else{
   res.status(500).send({"err":comment})
}
```

2020-08-27 16:03 UTC, ChoukseyKhushbu requested changes
Test the API call once after changing the code as I have just written the code without making a call.

2020-08-28 04:46 UTC, adad20 commented
@ChoukseyKhushbu I think this looks good now

2020-08-28 07:30 UTC, ChoukseyKhushbu approved these changes

2020-08-28 07:36 UTC, merged